import { Feed, FeedImage } from "@/features/lounge/infrastructure/model/feed.model";
import { Category } from "@/features/lounge/infrastructure/model/category.model";
import { Profile } from "@/features/user/core/model/profile.model";
import { User, Agreement } from "@/features/user/core/model/user.model";

// 카테고리 더미 데이터
const categories: Category[] = [
  {
    _id: 1,
    name: "개발",
    subCategories: [
      { _id: 1, name: "프론트엔드", parentCategoryId: 1 },
      { _id: 2, name: "백엔드", parentCategoryId: 1 },
      { _id: 3, name: "데브옵스", parentCategoryId: 1 },
    ],
  },
  {
    _id: 2,
    name: "디자인",
    subCategories: [
      { _id: 4, name: "UI/UX", parentCategoryId: 2 },
      { _id: 5, name: "그래픽 디자인", parentCategoryId: 2 },
    ],
  },
  {
    _id: 3,
    name: "커리어",
    subCategories: [
      { _id: 6, name: "취업/이직", parentCategoryId: 3 },
      { _id: 7, name: "커리어 성장", parentCategoryId: 3 },
      { _id: 8, name: "면접", parentCategoryId: 3 },
    ],
  },
];

// 프로필 더미 데이터 (간소화된 버전)
const profiles: Profile[] = [
  {
    _id: "1",
    avatar: "https://avatars.githubusercontent.com/u/12345678",
    persona: {
      contact: {
        email: "kim.dev@example.com",
        github: "kimdev",
        blog: "https://kimdev.dev",
      },
      personal: {
        name: "김개발",
        description: "사용자 경험을 중요시하는 프론트엔드 개발자입니다.",
        job: "프론트엔드 개발자",
        personality: "ENFP",
        interests: ["웹 기술", "UI/UX", "오픈소스"],
      },
      identity: {
        frontend: "React, TypeScript, NextJS",
        backend: "Node.js, Express",
        tools: "Git, Docker, Figma",
      },
      location: {
        address: "서울시 강남구",
        education: "서울대학교",
        experience: "네이버, 카카오",
      },
    },
    skill: {
      techSkills: [
        { name: "React", image: "react.svg" },
        { name: "TypeScript", image: "typescript.svg" },
        { name: "NextJS", image: "nextjs.svg" },
      ],
      usableTools: [
        { name: "Git", image: "git.svg" },
        { name: "Docker", image: "docker.svg" },
        { name: "Figma", image: "figma.svg" },
      ],
    },
    experience: [
      {
        companyName: "네이버",
        companyLogo: "naver.svg",
        companyArea: "IT",
        team: "프론트엔드 개발팀",
        role: "시니어 개발자",
        summary: "웹 서비스 개발 및 유지보수",
        description: "네이버 메인 서비스 UI 개편 및 최적화 작업 수행.",
        period: [new Date("2020-01-01"), new Date("2023-12-31")],
        location: "경기도 성남시",
      },
    ],
    education: [
      {
        status: "졸업",
        school: "서울대학교",
        major: "컴퓨터공학과",
        degree: "학사",
        period: "2014-2018",
        description: "웹 개발 동아리 활동, 해커톤 다수 참가",
      },
    ],
    activity: {
      id: 1,
      title: "오픈소스 컨트리뷰션",
      description: "React 오픈소스 프로젝트에 기여",
      period: ["2021-01", "2022-12"],
      role: "컨트리뷰터",
      team: "React Community",
      location: "온라인",
      isPublic: true,
      createdAt: "2021-01-01T00:00:00Z",
      updatedAt: null,
      deletedAt: null,
    },
    garage: {
      id: "garage1",
      title: "개인 포트폴리오 웹사이트",
      description: "React와 TypeScript를 사용한 개인 포트폴리오 웹사이트",
      period: ["2022-01", "2022-03"],
      role: "개발자",
      team: "개인 프로젝트",
      location: "온라인",
      isPublic: true,
      url: "https://github.com/kimdev/portfolio",
      language: "TypeScript",
      stars: 25,
      forks: 5,
      createdAt: "2022-01-01T00:00:00Z",
      updatedAt: "2022-03-15T00:00:00Z",
      deletedAt: null,
    },
    user: {
      _id: 1,
      uuid: "a1b2c3d4-e5f6-7890-abcd-1234567890ab",
      username: "kimdev",
      nickname: "김개발",
      email: "kim.dev@example.com",
      agreements: {
        privacyPolicy: true,
        terms: true,
        notMinority: true,
      },
      createdAt: "2020-01-01T00:00:00Z",
      updatedAt: "2023-01-01T00:00:00Z",
      deletedAt: null,
    },
    createdAt: "2020-01-01T00:00:00Z",
    updatedAt: "2023-01-01T00:00:00Z",
    deleteAt: "",
  },
  {
    _id: "2",
    avatar: "https://avatars.githubusercontent.com/u/87654321",
    persona: {
      contact: {
        email: "lee.backend@example.com",
        github: "leebackend",
        blog: "https://leebackend.dev",
      },
      personal: {
        name: "이백엔드",
        description: "확장성 있는 서버 아키텍처를 설계하는 백엔드 개발자입니다.",
        job: "백엔드 개발자",
        personality: "INTJ",
        interests: ["분산 시스템", "클라우드", "데이터베이스"],
      },
      identity: {
        frontend: "Vue.js, JavaScript",
        backend: "Spring Boot, Java, Kotlin",
        tools: "AWS, Jenkins, Kubernetes",
      },
      location: {
        address: "서울시 서초구",
        education: "카이스트",
        experience: "라인, 쿠팡",
      },
    },
    skill: {
      techSkills: [
        { name: "Spring Boot", image: "spring.svg" },
        { name: "Java", image: "java.svg" },
        { name: "Kotlin", image: "kotlin.svg" },
      ],
      usableTools: [
        { name: "AWS", image: "aws.svg" },
        { name: "Jenkins", image: "jenkins.svg" },
        { name: "Kubernetes", image: "kubernetes.svg" },
      ],
    },
    experience: [],
    education: [],
    activity: {
      id: 2,
      title: "기술 블로그 운영",
      description: "Spring과 MSA에 관한 기술 블로그 운영",
      period: ["2020-01", "2023-05"],
      role: "운영자",
      team: "개인 활동",
      location: "온라인",
      isPublic: true,
      createdAt: "2020-01-01T00:00:00Z",
      updatedAt: "2023-05-10T00:00:00Z",
      deletedAt: null,
    },
    garage: {
      id: "garage2",
      title: "분산 메시징 시스템",
      description: "고가용성을 갖춘 분산 메시징 시스템 프로토타입",
      period: ["2021-04", "2021-12"],
      role: "개발자",
      team: "개인 프로젝트",
      location: "온라인",
      isPublic: true,
      url: "https://github.com/leebackend/distributed-messaging",
      language: "Java",
      stars: 78,
      forks: 15,
      createdAt: "2021-04-01T00:00:00Z",
      updatedAt: "2021-12-15T00:00:00Z",
      deletedAt: null,
    },
    user: {
      _id: 2,
      uuid: "b2c3d4e5-f6g7-8901-bcde-2345678901cd",
      username: "leebackend",
      nickname: "이백엔드",
      email: "lee.backend@example.com",
      agreements: {
        privacyPolicy: true,
        terms: true,
        notMinority: true,
      },
      createdAt: "2019-01-01T00:00:00Z",
      updatedAt: "2023-02-01T00:00:00Z",
      deletedAt: null,
    },
    createdAt: "2019-01-01T00:00:00Z",
    updatedAt: "2023-02-01T00:00:00Z",
    deleteAt: "",
  },
  {
    _id: "3",
    avatar: "https://avatars.githubusercontent.com/u/11223344",
    persona: {
      contact: {
        email: "park.devops@example.com",
        github: "parkdevops",
        blog: "https://parkdevops.dev",
      },
      personal: {
        name: "박데브옵스",
        description: "인프라 자동화와 클라우드 아키텍처를 전문으로 하는 데브옵스 엔지니어입니다.",
        job: "데브옵스 엔지니어",
        personality: "ISTJ",
        interests: ["클라우드", "자동화", "보안"],
      },
      identity: {
        frontend: "HTML, CSS, JavaScript",
        backend: "Python, Go",
        tools: "Terraform, Ansible, AWS, K8s",
      },
      location: {
        address: "서울시 송파구",
        education: "연세대학교",
        experience: "토스, 당근마켓",
      },
    },
    skill: {
      techSkills: [
        { name: "Kubernetes", image: "kubernetes.svg" },
        { name: "Docker", image: "docker.svg" },
        { name: "Terraform", image: "terraform.svg" },
      ],
      usableTools: null,
    },
    experience: [],
    education: [],
    activity: {
      id: 3,
      title: "클라우드 네이티브 스터디 그룹",
      description: "CNCF 기술 스터디 그룹 운영",
      period: ["2020-03", "2023-04"],
      role: "운영자",
      team: "Cloud Native Korea",
      location: "서울",
      isPublic: true,
      createdAt: "2020-03-01T00:00:00Z",
      updatedAt: "2023-04-15T00:00:00Z",
      deletedAt: null,
    },
    garage: {
      id: "garage3",
      title: "인프라 자동화 도구",
      description: "Terraform과 Ansible을 활용한 인프라 자동화 도구",
      period: ["2021-02", "2021-08"],
      role: "개발자",
      team: "개인 프로젝트",
      location: "온라인",
      isPublic: true,
      url: "https://github.com/parkdevops/infra-automation",
      language: "Go",
      stars: 120,
      forks: 35,
      createdAt: "2021-02-01T00:00:00Z",
      updatedAt: "2021-08-15T00:00:00Z",
      deletedAt: null,
    },
    user: {
      _id: 3,
      uuid: "c3d4e5f6-g7h8-9012-cdef-3456789012ef",
      username: "parkdevops",
      nickname: "박데브옵스",
      email: "park.devops@example.com",
      agreements: {
        privacyPolicy: true,
        terms: true,
        notMinority: true,
      },
      createdAt: "2018-01-01T00:00:00Z",
      updatedAt: "2023-03-01T00:00:00Z",
      deletedAt: null,
    },
    createdAt: "2018-01-01T00:00:00Z",
    updatedAt: "2023-03-01T00:00:00Z",
    deleteAt: "",
  },
];

// 피드 이미지 더미 데이터
const feedImages: FeedImage[] = [
  { url: "https://example.com/images/react-typescript.jpg", order: 1 },
  { url: "https://example.com/images/spring-benchmark.png", order: 1 },
  { url: "https://example.com/images/virtual-thread-diagram.jpg", order: 2 },
  { url: "https://example.com/images/kubernetes-hpa.png", order: 1 },
  { url: "https://example.com/images/nextjs-performance.png", order: 1 },
  { url: "https://example.com/images/gitops-workflow.jpg", order: 1 },
  { url: "https://example.com/images/graphql-rest.png", order: 1 },
  { url: "https://example.com/images/web-accessibility.jpg", order: 1 },
  { url: "https://example.com/images/cloud-cost.png", order: 1 },
  { url: "https://example.com/images/db-migration.jpg", order: 1 },
];

// 피드 더미 데이터 생성
export const feeds: Feed[] = [
  {
    _id: 1,
    category: categories[0],
    profile: profiles[0],
    author: {
      name: "김개발",
      avatar: "https://avatars.githubusercontent.com/u/12345678",
      title: "프론트엔드 개발자",
      shortDescription: "React와 TypeScript를 사랑하는",
    },
    content:
      "React 18과 TypeScript 5.0의 조합으로 새 프로젝트를 시작했습니다. 타입 안정성이 정말 좋아졌네요. 특히 새로운 기능들이 인상적입니다. 여러분은 어떤 프론트엔드 기술 스택을 선호하시나요?",
    views: 128,
    likes: 24,
    comments: 5,
    shares: 3,
    createdAt: "2024-01-15T09:30:00Z",
    images: [feedImages[0]],
  },
  {
    _id: 2,
    category: categories[0],
    profile: profiles[1],
    author: {
      name: "이백엔드",
      avatar: "https://avatars.githubusercontent.com/u/87654321",
      title: "백엔드 개발자",
      shortDescription: "Spring과 MSA를 좋아하는",
    },
    content:
      "Spring Boot 3.0에서 Virtual Thread를 적용해봤습니다. 기존 대비 성능이 크게 개선되었어요. 벤치마크 결과를 공유드립니다. 100K 동시 요청에서 기존 대비 처리량 40% 향상, 레이턴시 30% 감소를 확인했습니다.",
    views: 95,
    likes: 42,
    comments: 15,
    shares: 8,
    createdAt: "2024-01-14T14:20:00Z",
    images: [feedImages[1], feedImages[2]],
  },
  {
    _id: 3,
    category: categories[0],
    profile: profiles[2],
    author: {
      name: "박데브옵스",
      avatar: "https://avatars.githubusercontent.com/u/11223344",
      title: "데브옵스 엔지니어",
      shortDescription: "클라우드와 자동화를 사랑하는",
    },
    content:
      "K8s 클러스터 운영 중 겪은 트러블슈팅 경험을 공유합니다. Pod 자동 확장 관련 이슈였는데요, HPA(Horizontal Pod Autoscaler)가 제대로 작동하지 않아 부하 테스트 중 서비스 다운이 발생했습니다. 원인은 메트릭 서버와의 통신 문제였습니다. 자세한 해결 과정을 블로그에 정리했으니 참고하세요.",
    views: 156,
    likes: 32,
    comments: 8,
    shares: 12,
    createdAt: "2024-01-13T10:45:00Z",
    images: [feedImages[3]],
  },
  {
    _id: 4,
    category: categories[0],
    profile: profiles[1],
    author: {
      name: "이백엔드",
      avatar: "https://avatars.githubusercontent.com/u/87654321",
      title: "백엔드 개발자",
      shortDescription: "Spring과 MSA를 좋아하는",
    },
    content:
      "NestJS가 정말 좋아요. Express의 간결함과 Angular의 구조적 장점을 모두 갖추고 있어 대규모 백엔드 프로젝트에 적합합니다. TypeScript와의 통합도 완벽하고요. 최근에 NestJS로 마이크로서비스 아키텍처를 구현해봤는데, 모듈화와 유지보수 측면에서 큰 이점이 있었습니다.",
    views: 78,
    likes: 18,
    comments: 7,
    shares: 4,
    createdAt: "2024-01-12T16:30:00Z",
  },
  {
    _id: 5,
    category: categories[0],
    profile: profiles[0],
    author: {
      name: "김개발",
      avatar: "https://avatars.githubusercontent.com/u/12345678",
      title: "프론트엔드 개발자",
      shortDescription: "React와 TypeScript를 사랑하는",
    },
    content:
      "Next.js 14의 서버 컴포넌트와 새로운 앱 라우터를 적용한 프로젝트를 완성했습니다. 클라이언트 번들 사이즈가 40% 감소하고 초기 로딩 속도가 확실히 개선되었어요. SEO도 자연스럽게 향상되는 효과가 있었습니다. RSC(React Server Components)는 확실히 게임 체인저인 것 같습니다.",
    views: 214,
    likes: 56,
    comments: 23,
    shares: 15,
    createdAt: "2024-01-11T11:15:00Z",
    images: [feedImages[4]],
  },
  {
    _id: 6,
    category: categories[0],
    profile: profiles[2],
    author: {
      name: "박데브옵스",
      avatar: "https://avatars.githubusercontent.com/u/11223344",
      title: "데브옵스 엔지니어",
      shortDescription: "클라우드와 자동화를 사랑하는",
    },
    content:
      "GitOps 기반 배포 파이프라인을 구축하면서 ArgoCD와 Flux를 비교 검토했습니다. 결국 ArgoCD를 선택했는데, UI의 직관성과 다양한 확장 기능이 결정적이었습니다. 특히 멀티 클러스터 환경에서의 관리 편의성이 뛰어났어요. 다른 GitOps 도구를 사용하시는 분들의 경험도 궁금합니다.",
    views: 102,
    likes: 29,
    comments: 12,
    shares: 6,
    createdAt: "2024-01-10T13:40:00Z",
    images: [feedImages[5]],
  },
  {
    _id: 7,
    category: categories[0],
    profile: profiles[1],
    author: {
      name: "이백엔드",
      avatar: "https://avatars.githubusercontent.com/u/87654321",
      title: "백엔드 개발자",
      shortDescription: "Spring과 MSA를 좋아하는",
    },
    content:
      "GraphQL과 Rest API를 함께 사용하는 하이브리드 아키텍처를 도입해봤습니다. 각각의 장단점을 상호 보완하니 효율적인 API 설계가 가능하더군요. 기존 REST API는 그대로 유지하면서, 복잡한 데이터 조회가 필요한 부분만 GraphQL로 구현했습니다. 마이그레이션 부담도 줄이고 클라이언트 개발자들의 만족도도 높았습니다.",
    views: 145,
    likes: 37,
    comments: 14,
    shares: 9,
    createdAt: "2024-01-09T15:20:00Z",
    images: [feedImages[6]],
  },
  {
    _id: 8,
    category: categories[0],
    profile: profiles[0],
    author: {
      name: "김개발",
      avatar: "https://avatars.githubusercontent.com/u/12345678",
      title: "프론트엔드 개발자",
      shortDescription: "React와 TypeScript를 사랑하는",
    },
    content:
      "웹 접근성 개선 작업을 진행하면서 느낀 점을 공유합니다. 처음에는 단순히 WCAG 가이드라인 준수가 목표였지만, 실제로 개선 작업을 하다 보니 UX 전반이 향상되는 효과가 있었습니다. 특히 키보드 내비게이션과 스크린 리더 지원을 개선하는 과정에서 전체적인 사용성이 개선되었어요. 접근성은 선택이 아닌 필수라는 점을 다시 한번 느꼈습니다.",
    views: 189,
    likes: 45,
    comments: 18,
    shares: 20,
    createdAt: "2024-01-08T09:50:00Z",
    images: [feedImages[7]],
  },
  {
    _id: 9,
    category: categories[0],
    profile: profiles[2],
    author: {
      name: "박데브옵스",
      avatar: "https://avatars.githubusercontent.com/u/11223344",
      title: "데브옵스 엔지니어",
      shortDescription: "클라우드와 자동화를 사랑하는",
    },
    content:
      "클라우드 비용 최적화 프로젝트를 진행한 결과, 월 인프라 비용을 35% 절감했습니다. 주요 전략으로는 1) 리소스 사용량 모니터링 및 다운사이징, 2) 예약 인스턴스 활용, 3) 스팟 인스턴스 활용, 4) 오토스케일링 정책 최적화가 있었습니다. 특히 Lambda 함수의 메모리 설정 최적화만으로도 상당한 비용 절감 효과가 있었어요.",
    views: 276,
    likes: 62,
    comments: 25,
    shares: 30,
    createdAt: "2024-01-07T11:30:00Z",
    images: [feedImages[8]],
  },
  {
    _id: 10,
    category: categories[0],
    profile: profiles[1],
    author: {
      name: "이백엔드",
      avatar: "https://avatars.githubusercontent.com/u/87654321",
      title: "백엔드 개발자",
      shortDescription: "Spring과 MSA를 좋아하는",
    },
    content:
      "데이터베이스 마이그레이션(MySQL에서 PostgreSQL로)을 성공적으로 완료했습니다. 다운타임 없이 실시간 복제를 통해 마이그레이션을 진행했는데요, Debezium과 Kafka를 활용한 CDC(Change Data Capture) 패턴이 매우 효과적이었습니다. PostgreSQL의 JSON 타입과 고급 인덱싱 기능이 우리 서비스에 많은 이점을 가져다 주고 있습니다.",
    views: 164,
    likes: 33,
    comments: 11,
    shares: 8,
    createdAt: "2024-01-06T14:15:00Z",
    images: [feedImages[9]],
  },
];

export default feeds;
